name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Cache Docusaurus build
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('build/**') }}
          restore-keys: |
            ${{ runner.os }}-build-
