name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Restore Cache Build
        uses: actions/cache/restore@v3
        id: restore-cache-build
        with:
          path: node_modules/.cache
          key: build-cache

      - name: Run Build
        run: npm run build

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: build-cache
